[package]
name = "lua-env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.9", features = [] }
lua-util = { path = "../lua-util" }
relative-path = "1"
pathdiff = "0.2"
