[package]
name = "lua-date"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.9" }
chrono = { version = "0.4" }
lua-util = { path = "../lua-util" }
